### ISSUE TITLE
The number of messages in SOCVR is too damn high.

### ISSUE THREAD

**Issue by gunr2171** [jdd-software/SOCVFinder#8]
Queen messages posted in SOCVR are getting a bit too much, more than our cv-pls.

Here are my ideas to lower the report count:

1. Only allow a set number of reports per time frame. For example: `5 reports per 60 minutes`.
2. Only report when some part of the post as reached a threshold, like the score is < -1.

These two options however dilute the speedyness of the reporting system. If the point of the bot is to allow people to dup-hammer quickly on newly created posts, these options are less than ideal.

Two other options:

1. Don't ping people in SOCVR, ping them in the SOCVFinder room. (Doesn't really solve the "massive number of reports in SOCVR problem)
2. Instead of posting each report in SOCVR, tell a user
  
  > There are 3 [tag:possible-duplicate] posts created recently in your watched tags. View them [here].

  The link would send you to the first message in SOCVFinder.

<sub>[Title reference](https://en.wikipedia.org/wiki/Rent_Is_Too_Damn_High_Party)</sub>

**Comment by Tunaki** [comment]
@gunr2171  Another possibility is removing the PHP tag from the current tags. It was added recently, and it does bring a lot of new messages.

New question: we need stats on the number of possible-duplicate messages per tag. I will be able to do that when I get home, access to the DB and a wonderful Azerty keyboard!!!!!!!

**Comment by Bhargav-Rao** [comment]
Why aren't queen's messages moved to the Graveyard? Just like cv-pls, the [possible-duplicate] requests are also a request for a "binding" close vote. Yes, the number won't be reduced in this case, but it will make the transcript look less cluttered. 

Another idea is to make queen delete the message, (Instead of scratching out the question), on sending a 'f'. A 'k' perhaps could be acknowledged in a different way to allow it to be moved from the room.

**Comment by Tunaki** [comment]
@Bhargav-Rao Feedback can come well after the 2 minutes window allowed for editing (or deleting) the message so you can't rely on chat to determine if a possible-dupe was reviewed. The solution is to make an API that would return the status of a reported question (closed or deleted / feedback f / feedback k) so that a userscript could query it and determine if the messsages needs to be moved or not (also, such API needs to be hosted somewhere _looks at @Sam_)

**Comment by ArcticEcho** [comment]
Sure, I can write the backend/host it, if you guys do indeed decide to take that path.

**Comment by Tunaki** [comment]
Simpler solution implemented: messages posted by Queen and their feedbacks are moved to the GraveYard when running the archiver script. It will take into account only messages posted more than 30 minutes ago.
